name: Ejecutar Bot desde 1:25 AM hasta 7 AM
on:
  schedule:
    - cron: "25 6-11/1 * * *"  # Inicia a las 6:25 UTC (1:25 AM COL) y cada 1 hora
  workflow_dispatch:           # Permite ejecución manual desde "Actions"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Python y Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip chromium-browser chromium-chromedriver

      - name: Instalar dependencias de Python
        run: pip3 install -r requirements.txt

      - name: Ejecutar el script (con pantalla virtual)
        run: xvfb-run -a python3 tu_script.py  # xvfb simula una interfaz gráfica

