name: Ejecutar Bot desde 12 AM hasta 4 PM (COL)
on:
  schedule:
    - cron: "0 5-21 * * *"  # Medianoche COL (5 UTC) hasta 4 PM COL (21 UTC), cada hora en punto.
  workflow_dispatch:         # Ejecución manual desde "Actions"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Python y Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip chromium-browser chromium-chromedriver

      - name: Instalar dependencias de Python
        run: pip3 install -r requirements.txt

      - name: Ejecutar el script (con pantalla virtual)
        run: xvfb-run -a python3 tu_script.py

